// Copy and demo data are shared by the page components and contract tests.
export const copy = {
  no: {
    skip:'Hopp til innholdet', navigation:'Hovedmeny', mobileNavigation:'Mobilmeny', openMenu:'Åpne meny', closeMenu:'Lukk meny', close:'Lukk',
    title:'Scope — Fra tall til neste trekk', description:'Scope samler restaurantens tall og gjør dem til konkrete råd om bemanning, meny og lønnsomhet. Få oversikt. Vit hva du bør gjøre videre.',
    navProduct:'Produktet', navRecommendations:'Anbefalingene', navConnections:'Slik henger det sammen', book:'Book en demo',
    heroEyebrow:'Et klarere blikk på restaurantdriften', heroOne:'Tallene er der.', heroTwo:'Neste trekk er her.', heroDescription:'Scope samler restaurantens data og viser hva du kan gjøre for å drive litt smartere. Hver dag.', seeProduct:'Ta en titt på Scope', heroNote:'For deg som driver restaurant. Ikke regneark.',
    productPreview:'Interaktiv produktvisning', restaurantCity:'Oslo', demoData:'Demodata', yourOverview:'DIN OVERSIKT', greeting:'God morgen, Anna.', briefing:'Det går bra. Her er det som kan bli enda bedre.', period:'Periode', today:'I dag', thisWeek:'Denne uken', explore:'Utforsk Scope', overview:'Oversikt', menuProfit:'Menylønnsomhet', staffing:'Bemanning', dashboardDisclaimer:'Eksempelrestaurant · Illustrative tall og estimater, ikke faktiske resultater.', productCaption:'Hele bildet. Én rolig arbeidsflate.',
    recommendEyebrow:'Fra innsikt til handling', recommendHeadingOne:'Et tall sier noe.', recommendHeadingTwo:'Et godt råd tar deg videre.', recommendDescription:'Andre systemer viser deg tallene. Scope viser deg hva du bør gjøre med dem – og hvorfor.', chooseRecommendation:'Velg anbefaling',
    connectionEyebrow:'Se sammenhengen', connectionHeadingOne:'Du har dataene.', connectionHeadingTwo:'Vi samler trådene.', connectionDescription:'Kassen vet hva du solgte. Vaktlisten vet hvem som jobbet. Scope setter tallene i sammenheng, så du slipper.', connectionNote:'I demoen avklarer vi hvilke av systemene dine som kan kobles til.', exploreSources:'Utforsk datakildene', pos:'Kasse', accounts:'Regnskap', bookings:'Booking',
    workflowEyebrow:'Mindre analyse. Mer handling.', workflowHeading:'En bedre start på arbeidsdagen.', stepOne:'Koble sammen.', stepOneDescription:'Samle tallene fra systemene du allerede bruker. Behold rutinene som fungerer.', stepTwo:'Forstå det viktigste.', stepTwoDescription:'Se hva som går bra, hva som skiller seg ut, og hvor du bør rette oppmerksomheten.', stepThree:'Ta neste trekk.', stepThreeDescription:'Velg et konkret tiltak. Følg utviklingen og se om det faktisk gjør en forskjell.',
    finalEyebrow:'Mer tid til det du kan best', finalHeadingOne:'Litt mindre gjetting.', finalHeadingTwo:'Litt mer restaurant.', finalDescription:'Se hva Scope kan bety for din restaurant. Vi begynner med en kort prat.', noObligation:'En uforpliktende gjennomgang. Med et menneske.', footerTagline:'Klarhet i tallene. Retning i hverdagen.', contact:'Kontakt', privacy:'Personvern',
    demoEyebrow:'Din restaurant, i fokus', demoTitle:'La oss vise deg Scope.', demoDescription:'Fortell oss litt om restauranten din. Vi avtaler et tidspunkt og går gjennom det som er relevant for deg.', yourName:'Navnet ditt', yourRestaurant:'Restauranten din', openDraft:'Åpne e-postutkast', draftNote:'Åpner e-postappen din med et ferdig utkast. Ingenting sendes før du selv trykker send.', draftStatus:'Utkastet åpnes i e-postappen din. Hvis det ikke åpnes, kan du skrive direkte til post@scopeanalytics.no.', emailSubject:'Demo av Scope',
    privacyText:'Denne siden bruker ingen analyse- eller markedsføringsinformasjonskapsler. Vi lagrer kun språkvalget ditt i nettleseren. Produktvisningen bruker fiktive restaurantdata.', privacyEmail:'Demoforespørselen åpnes i din egen e-postapp. Opplysningene sendes bare til Scope når du selv sender e-posten, og brukes til å følge opp henvendelsen. Du kan kontakte oss om innsyn eller sletting.',
    revenue:'Omsetning', laborCost:'Lønnskostnad', foodCost:'Varekostnad', estimatedProfit:'Estimert resultat', vsPrevious:'mot forrige periode', vsTarget:'mot mål', points:'pp.', allCosts:'Etter estimerte kostnader', revenueChart:'Omsetning mot mål', actual:'Omsetning', target:'Mål', guests:'Gjester', takeawayOrders:'Takeaway-bestillinger', recommends:'Scope anbefaler', priorities:'Prioriterte tiltak', currency:'kr', possibleEffect:'Mulig effekt per uke', ordinaryDashboard:'Tallet alene', contextMissing:'Du ser tallet. Men hva gjør du med det?',
    topDishes:'Hva tjener du på hver rett?', dishDescription:'Pris og råvarer per porsjon, ekskl. mva.', averageMargin:'Snittbidrag', dish:'Rett', price:'Pris', food:'Råvarer', sold:'Solgt', margin:'Bidrag', menuNote:'Bidrag = pris minus råvarer. Lønn og andre kostnader er ikke trukket fra. Eksempeldata.', highMargin:'Høyest bidrag', lowMargin:'Se nærmere på',
    staffingHeading:'Riktig bemanning. Til riktig tid.', staffingDescription:'Planlagte ansatte sammenlignet med anslått behov.', scheduled:'Planlagt', needed:'Anslått behov', people:'ansatte', staffingInsight:'Rolig mellom 15 og 17.', staffingWhy:'Fire ansatte er satt opp, men salget tilsier et behov for to. Vurder å flytte én vakt til kveldsrushet.', inspectRecommendation:'Se anbefalingen', sourceDetail:'Datakilden i sammenheng', dayLabels:['12','13:30','15','16:30','18','19:30','21','22:30'], weekLabels:['Man','Tir','Ons','Tor','Fre','Lør','Søn'],
    miniStaff:'Tilpass vaktene kl. 15–17', miniStaffDetail:'Mulig effekt: 3 200 kr / uke', miniMenu:'Se på prisen på carbonara', miniMenuDetail:'23 % lavere bidrag enn menysnittet', miniTakeaway:'Gi takeaway mer plass i kveld', miniTakeawayDetail:'Lav borddekning, høy etterspørsel',
    scenarios: {
      staffing:{metric:'Lønnskostnad i dag',value:'37,4 %',title:'Én færre på vakt. Når det faktisk er rolig.',description:'Lønnskostnaden er høy mellom kl. 15 og 17. Vurder én færre på vakt i dette tidsrommet, og behold kapasiteten gjennom middagsrushet.',effect:'3 200 kr',assumption:'Eksempel: 2 timer × 320 kr × 5 dager. Forutsetter at bemanningen fortsatt dekker behovet.'},
      menu:{metric:'Bidrag på Pasta Carbonara',value:'50,6 %',title:'En populær rett. Med mer å gå på.',description:'Carbonara har 23 % lavere bidragsprosent enn menysnittet på 65,7 %. Se på porsjon, råvarebruk eller pris. En prisøkning på 20 kr gir 20 kr mer i bidrag per rett.',effect:'1 840 kr',assumption:'Eksempel: 20 kr × 92 porsjoner per uke. Forutsetter uendret salg og råvarekost. Ekskl. mva.'},
      takeaway:{metric:'Forventet borddekning i kveld',value:'42 %',title:'Færre bord booket. En annen mulighet.',description:'Bookingene er under normalen på 68 %. Samtidig pleier takeaway å gå godt denne kvelden. Løft frem to retter med godt bidrag i takeaway-menyen.',effect:'1 200 kr',assumption:'Eksempel: 10 ekstra bestillinger × 120 kr i bidrag etter råvarer, emballasje og leveringsgebyr. Før lønn.'}
    },
    sources:{pos:{title:'Fra salg til mønster.',description:'Se hvilke retter og timer som bidrar mest. Sammenlign med råvarer og bemanning.'},accounts:{title:'Hele kostnadsbildet.',description:'Se om økt omsetning faktisk gir bedre resultat når kostnadene tas med.'},staffing:{title:'Folk når det trengs.',description:'Sammenhold vakter med salg og booking. Finn timene med for høy bemanning.'},bookings:{title:'Ligg litt i forkant.',description:'Se rolige kvelder før de kommer. Planlegg bemanning og tiltak i tide.'},takeaway:{title:'Flere veier til salg.',description:'Se når takeaway kan fylle ledig kapasitet, og hva du sitter igjen med etter gebyrer.'}}
  },
  en: {
    skip:'Skip to content', navigation:'Main navigation', mobileNavigation:'Mobile navigation', openMenu:'Open menu', closeMenu:'Close menu', close:'Close',
    title:'Scope — Your numbers. Your next move.', description:'Scope connects your restaurant data and turns it into clear recommendations for staffing, menu margins and profitability. Know what to do next.',
    navProduct:'The product', navRecommendations:'Recommendations', navConnections:'How it connects', book:'Book a demo',
    heroEyebrow:'A clearer view of your restaurant', heroOne:'Your numbers.', heroTwo:'Your next move.', heroDescription:'Scope brings your restaurant data together and turns it into clear actions. A smarter way to run every day.', seeProduct:'Take a look inside', heroNote:'For people who run restaurants. Not spreadsheets.',
    productPreview:'Interactive product preview', restaurantCity:'Oslo', demoData:'Demo data', yourOverview:'YOUR OVERVIEW', greeting:'Good morning, Anna.', briefing:'Things look good. Here’s what could be even better.', period:'Period', today:'Today', thisWeek:'This week', explore:'Explore Scope', overview:'Overview', menuProfit:'Menu profitability', staffing:'Staffing', dashboardDisclaimer:'Example restaurant · Illustrative figures and estimates, not actual results.', productCaption:'The whole picture. One calm workspace.',
    recommendEyebrow:'From insight to action', recommendHeadingOne:'A number tells you something.', recommendHeadingTwo:'Good advice moves you forward.', recommendDescription:'Other systems show you the numbers. Scope shows you what to do about them, and why.', chooseRecommendation:'Choose a recommendation',
    connectionEyebrow:'Connect the dots', connectionHeadingOne:'The data is already there.', connectionHeadingTwo:'Let’s make it useful.', connectionDescription:'Your till knows what sold. Your roster knows who worked. Scope puts the pieces together, so you don’t have to.', connectionNote:'In your demo, we’ll confirm which of your systems can connect.', exploreSources:'Explore data sources', pos:'Point of sale', accounts:'Accounting', bookings:'Bookings',
    workflowEyebrow:'Less analysis. More action.', workflowHeading:'A better way to start your day.', stepOne:'Bring it together.', stepOneDescription:'Connect the numbers from the systems you already use. Keep the routines that work.', stepTwo:'See what matters.', stepTwoDescription:'Know what’s going well, what stands out, and where your attention will make a difference.', stepThree:'Make your next move.', stepThreeDescription:'Choose a practical action. Follow the trend and see whether it makes a real difference.',
    finalEyebrow:'More time for what you do best', finalHeadingOne:'Less guesswork.', finalHeadingTwo:'More restaurant.', finalDescription:'See what Scope could mean for your restaurant. Let’s start with a conversation.', noObligation:'A personal walkthrough. No commitment.', footerTagline:'Clarity in your numbers. Direction in your day.', contact:'Contact', privacy:'Privacy',
    demoEyebrow:'Your restaurant comes first', demoTitle:'Let’s show you Scope.', demoDescription:'Tell us a little about your restaurant. We’ll arrange a time and walk you through what matters to you.', yourName:'Your name', yourRestaurant:'Your restaurant', openDraft:'Open email draft', draftNote:'Opens a prepared message in your email app. Nothing is sent until you press send yourself.', draftStatus:'Your draft opens in your email app. If it doesn’t open, write directly to post@scopeanalytics.no.', emailSubject:'A demo of Scope',
    privacyText:'This page uses no analytics or marketing cookies. We only save your language preference in your browser. The product preview uses fictional restaurant data.', privacyEmail:'Demo requests open in your own email app. Your details only reach Scope when you send the email, and are used to respond to your enquiry. Contact us to request access to or deletion of your information.',
    revenue:'Revenue', laborCost:'Labor cost', foodCost:'Food cost', estimatedProfit:'Estimated profit', vsPrevious:'vs. previous period', vsTarget:'vs. target', points:'pp', allCosts:'After estimated costs', revenueChart:'Revenue vs. target', actual:'Revenue', target:'Target', guests:'Guests', takeawayOrders:'Takeaway orders', recommends:'Scope recommends', priorities:'Priority actions', currency:'NOK', possibleEffect:'Potential weekly effect', ordinaryDashboard:'The number alone', contextMissing:'You can see the number. But what should you do?',
    topDishes:'What does each dish earn?', dishDescription:'Price and ingredient cost per serving, excluding VAT.', averageMargin:'Average margin', dish:'Dish', price:'Price', food:'Ingredients', sold:'Sold', margin:'Margin', menuNote:'Contribution = price less ingredients. Labor and other costs are not deducted. Example data.', highMargin:'Highest margin', lowMargin:'Worth a closer look',
    staffingHeading:'The right people. At the right time.', staffingDescription:'Scheduled staff compared with estimated demand.', scheduled:'Scheduled', needed:'Estimated need', people:'staff', staffingInsight:'A quiet spell from 3 to 5.', staffingWhy:'Four people are scheduled, but sales suggest a need for two. Consider moving one shift to the evening rush.', inspectRecommendation:'See the recommendation', sourceDetail:'Data in context', dayLabels:['12','13:30','15','16:30','18','19:30','21','22:30'], weekLabels:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    miniStaff:'Adjust staffing from 3–5 pm', miniStaffDetail:'Potential: NOK 3,200 / week', miniMenu:'Review the price of carbonara', miniMenuDetail:'Margin is 23% below the menu average', miniTakeaway:'Make more of takeaway tonight', miniTakeawayDetail:'Fewer bookings, strong takeaway demand',
    scenarios: {
      staffing:{metric:'Today’s labor cost',value:'37.4%',title:'One fewer on shift. When it’s actually quiet.',description:'Labor costs run high between 3 and 5 pm. Consider one fewer person during this window, while keeping capacity for the dinner rush.',effect:'NOK 3,200',assumption:'Example: 2 hours × NOK 320 × 5 days. Assumes the remaining team can meet demand.'},
      menu:{metric:'Pasta Carbonara margin',value:'50.6%',title:'A popular dish. With room to improve.',description:'Carbonara’s margin is 23% below the menu average of 65.7%. Review the portion, ingredients or price. A NOK 20 price increase adds NOK 20 in contribution per dish.',effect:'NOK 1,840',assumption:'Example: NOK 20 × 92 servings per week. Assumes unchanged sales and ingredient costs. Excluding VAT.'},
      takeaway:{metric:'Expected table occupancy tonight',value:'42%',title:'Fewer tables booked. Another opportunity.',description:'Bookings are below the usual 68%. Yet takeaway demand is typically strong this evening. Give two high-margin dishes more visibility on your takeaway menu.',effect:'NOK 1,200',assumption:'Example: 10 extra orders × NOK 120 contribution after ingredients, packaging and delivery fees. Before labor.'}
    },
    sources:{pos:{title:'From sales to patterns.',description:'See which dishes and hours contribute most. Connect them with ingredients and staffing.'},accounts:{title:'The full cost picture.',description:'See whether higher revenue really means better profit once costs are accounted for.'},staffing:{title:'People when you need them.',description:'Match shifts with sales and bookings. Find the hours when you’re overstaffed.'},bookings:{title:'Stay one step ahead.',description:'Spot quiet evenings before they arrive. Plan your team and your response in time.'},takeaway:{title:'Another way to grow.',description:'See when takeaway can fill spare capacity, and what you keep after delivery fees.'}}
  }
};

export const periods = {
  day:{revenue:48650,labor:37.4,food:28.1,other:16,profit:9000,change:8.2,guests:164,takeaway:28,values:[1400,2300,3100,4200,5500,9600,12850,9700],targets:[2000,2500,4000,4500,5000,8000,11000,8000],labels:'dayLabels'},
  week:{revenue:284500,labor:31.8,food:27.6,other:22,profit:52917,change:12.8,guests:962,takeaway:186,values:[32000,38500,37200,41000,44600,48650,42550],targets:[34000,35000,35000,37000,42000,47000,40000],labels:'weekLabels'}
};
export const dishes = [
  {name:{no:'Sopprisotto',en:'Mushroom risotto'},price:225,cost:58,day:32,week:168},
  {name:{no:'Grillet laks',en:'Grilled salmon'},price:295,cost:96,day:24,week:124},
  {name:{no:'Bistroburger',en:'Bistro burger'},price:245,cost:86,day:40,week:214},
  {name:{no:'Pasta Carbonara',en:'Pasta Carbonara'},price:245,cost:121,day:17,week:92}
];
export const staff = [{hour:'12',scheduled:3,needed:3},{hour:'14',scheduled:4,needed:3},{hour:'15',scheduled:4,needed:2},{hour:'17',scheduled:5,needed:5},{hour:'19',scheduled:7,needed:7},{hour:'21',scheduled:5,needed:4}];
export function demoMailto(language, name, restaurant) {
  const c = copy[language] || copy.no;
  const body = language === 'en' ? `Hello Scope,\n\nI’d like a demo for ${restaurant}. Please get in touch to arrange a time.\n\nBest,\n${name}` : `Hei Scope,\n\nJeg ønsker en demo for ${restaurant}. Ta gjerne kontakt for å avtale et tidspunkt.\n\nVennlig hilsen\n${name}`;
  return `mailto:post@scopeanalytics.no?subject=${encodeURIComponent(c.emailSubject)}&body=${encodeURIComponent(body)}`;
}
